project:
  type: website

website:
  title: "Fun time with my LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto


